import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{html,js,svelte,ts}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1b",
        "on-tertiary-fixed": "#251a00",
        "surface-dim": "#131313",
        outline: "#849396",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#f3bf26",
        "surface-container-lowest": "#0e0e0e",
        "on-background": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "outline-variant": "#3b494c",
        surface: "#131313",
        "on-secondary-container": "#b7b5b4",
        "on-secondary": "#303030",
        "on-surface-variant": "#bac9cc",
        "surface-container": "#201f1f",
        "error-container": "#93000a",
        "surface-tint": "#00daf3",
        "inverse-primary": "#006875",
        "on-tertiary-container": "#6f5500",
        "on-secondary-fixed-variant": "#474746",
        secondary: "#c8c6c5",
        primary: "#c3f5ff",
        "primary-container": "#00e5ff",
        background: "#131313",
        "primary-fixed": "#9cf0ff",
        "on-error": "#690005",
        "surface-bright": "#393939",
        "primary-fixed-dim": "#00daf3",
        "inverse-surface": "#e5e2e1",
        "on-tertiary": "#3e2e00",
        "on-secondary-fixed": "#1b1b1c",
        tertiary: "#ffeac0",
        error: "#ffb4ab",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed-variant": "#594400",
        "on-primary-fixed-variant": "#004f58",
        "secondary-fixed": "#e5e2e1",
        "secondary-container": "#474746",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#ffdf96",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#313030",
        "on-primary": "#00363d",
        "on-primary-container": "#00626e",
        "on-primary-fixed": "#001f24",
        "tertiary-container": "#fec931",
        "secondary-fixed-dim": "#c8c6c5",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [forms, containerQueries],
};
